apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.secret.name }}
    namespace: {{ .Values.namespace }}
type: Opaque
data:
    username: {{ .Values.secret.data.username }}
    password: {{ .Values.secret.data.password }}
    root_password: {{ .Values.secret.data.root_password }}
