apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: disk.csi.azure.com
  name: spring-mysql-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  csi:
    driver: disk.csi.azure.com
    volumeHandle: /subscriptions/71d131e2-d168-45ca-9afe-06ed2ae2e20f/resourceGroups/sp_aks_group/providers/Microsoft.Compute/disks/myAKSDisk
    volumeAttributes:
      fsType: ext4