apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.database.databaseName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.database.databaseName }}
spec:
  replicas: {{ .Values.database.replicaNumber }}
  selector:
    matchLabels:
      app: {{ .Values.database.databaseName }}
  template:
    metadata:
      labels:
        app: {{ .Values.database.databaseName }}
    spec:
      containers:
      - name: {{ .Values.database.databaseName }}
        image: {{ .Values.database.image }}
        ports:
        - containerPort: {{ .Values.database.port }}
        env:
        - name: {{ .Values.database.environment.username }}
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.name}}
              key: username
        - name: {{ .Values.database.environment.password }}
          valueFrom: 
            secretKeyRef:
              name: {{ .Values.secret.name}}
              key: password
        - name: {{ .Values.database.environment.rootPassword }}
          valueFrom: 
            secretKeyRef:
              name: {{ .Values.secret.name}}
              key: root_password
        - name: {{ .Values.database.environment.databaseName }}
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.configmap.name}}
              key: database_name
        volumeMounts:
        - name: {{ .Values.database.volume.name }}
          mountPath: {{ .Values.database.volume.mountPath }}
      volumes:
        - name: {{ .Values.database.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name}}
